### ISSUE TITLE
Add more community Server

### ISSUE THREAD

**Issue by FN-Florian** [Cobchise/CrewLinkStatus#28]
Hi @Cobchise ,
can you add more community servers? I have 3 servers in Germany that are a good alternative to the North American servers for European players.

http://s1.crewlink.de:9736/ (Germany - Frankfurt am Main)
http://s2.crewlink.de:9736/ (Germany - Frankfurt am Main)
http://s3.crewlink.de:9736/ (Germany - Nuremberg)

Kind Regards from Germany
Florian

**Comment by Cobchise** [comment]
I'd be happy to add these servers but for security reasons I'm requiring people to force https on their sites before I'll add them to the uptime site. 

If you enable https on these let me know and I'll add them. This can be achieved by either:

1. Passing `HTTPS` and `SSLPATH` environment variables to CrewLink-server on boot
2. Hosting the CrewLink server behind a reverse proxy (such as nginx) that routes via HTTPS and upgrades the websocket connection

I'd recommend option 2 as that would also allow you to proxy the sites in such a way that you can remove the port after the domain.

**Comment by Cobchise** [comment]
Added, thanks @FN-Florian ! Closing this issue but feel free to reach out here or on discord if you need anything!
